server:
    port: 8080
spring:
    application:
        name: team-5-backend
    datasource: 
        url: jdbc:h2:mem:testdb
    h2:
      console:
        enabled: true
    jpa:
        hibernate:
            ddl-auto: create
        
